### ISSUE TITLE
🐞 SHA256 mismatch on v0.9.0

### ISSUE THREAD

**Issue by ringods** [dagger/homebrew-tap#5]
### What is the issue?

I tried updating my Dagger setup to v0.9.0 via this Homebrew tap on my MacBook Pro (Apple M1) but got a `SHA256 mismatch` error.

### Log output

```
==> Fetching dagger/tap/dagger
==> Downloading https://dl.dagger.io/dagger/releases/0.9.0/dagger_v0.9.0_darwin_arm64.tar.gz
#################################################################################################################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: d5fcf9e4ca7c27b62bc789ede7fcbb66a0849f6f2bce07a5220cb0cb73b6a6ed
  Actual: ae589c0d6d655396a21257b684135486552b0c7dc6801c6326e25c8c979017aa
    File: /Users/ringods/Library/Caches/Homebrew/downloads/59177380499e1cfeb8738cdad71510ab2c5a0fd9f4c6ac5102283e26639491c2--dagger_v0.9.0_darwin_arm64.tar.gz
To retry an incomplete download, remove the file above.
```

Removing the file and retrying as indicated on the last line didn't help.

### Steps to reproduce

`brew install dagger/tap/dagger` on an M1/M2. It works on an Intel Mac.

### SDK version

N/A

### OS version

macOS 13.6 (22G120)

**Comment by gerhard** [comment]
Hey @ringods!

Thank you for reporting this - great catch! We fixed this part of:
- https://github.com/dagger/dagger/issues/5944

We are going to disable issues in this repository, and encourage everyone to use https://github.com/dagger/dagger/issues instead.

Thank you!
